### ISSUE TITLE
Implement `tune::last_fit()`

### ISSUE THREAD

**Issue by JavOrraca** [tidymodels/orbital#13]
In situations where a model was trained via hyperparameter tuning and finalized / re-fit with `tune::last_fit()`, I encounter the following error:

```{r}
Error in `orbital()`:
! Is not implemented for a <last_fit> object.
```

This {orbital} implementation would be excellent, and I'm loving this early stage package! 🚀

Two other observations and questions:

- I don't see a binding for `recipes::step_dummy()` in the package - Is this in the works?
- Will any {embed} functions be implemented with this? For example, `embed::step_lencode_mixed()` or `embed::step_lencode_glm()` (although, I fully recognize this would be a bear) 🙏

**Comment by JavOrraca** [comment]
Note: This would require support for `rsample::initial_split()` objects, etc.

**Comment by EmilHvitfeldt** [comment]
I have a handful of steps that will be able to be translated, step_dummy is on the list, as are many of the embed steps
